-- 상반기 + 7월 => top 3
SELECT FLAVOR
FROM(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM(
        SELECT * FROM FIRST_HALF
        UNION ALL
        SELECT * FROM JULY
    ) AS TOTAL_ORD
    GROUP BY FLAVOR
    ORDER BY TOTAL DESC
    LIMIT 3
) AS RESULT;
