-- 코드를 작성해주세요
SELECT YEAR(e.DIFFERENTIATION_DATE) AS YEAR, (sub.MS - e.SIZE_OF_COLONY) AS YEAR_DEV, e.ID
FROM ECOLI_DATA e
JOIN (
    SELECT MAX(SIZE_OF_COLONY) MS, YEAR(DIFFERENTIATION_DATE) AS year
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
sub ON YEAR(e.DIFFERENTIATION_DATE) = sub.year
ORDER BY YEAR ASC, YEAR_DEV ASC;